#!/bin/bash

# gShell
# 
# Copyright (C) LiveG. All Rights Reserved.
# 
# https://liveg.tech
# Licensed by the LiveG Open-Source Licence, which can be found at LICENCE.md.

tar \
    --exclude=.git \
    --exclude=.gitignore \
    --exclude=README.md \
    --exclude=LICENCE.md \
    --exclude=themegen \
    --exclude=buildarchive \
    --exclude=Adapt-UI-Linux.tar.gz \
    -czf Adapt-UI-Linux.tar.gz .